/**
 * Magic Square Grid (魔術方框) - Game Engine
 */

document.addEventListener('DOMContentLoaded', () => {
    // Game States
    let gridSize = 3;
    let difficulty = 'medium';
    let gameMode = 'fill';
    let board = [];       // 1D array representing current grid values (0 = empty)
    let clues = [];       // 1D array of booleans (true = fixed clue generated by game)
    let solution = [];    // 1D array representing the solved magic square
    
    // UI selections
    let selectedBankNum = null;
    let selectedGridCellIndex = null;
    
    // Stats
    let moveCount = 0;
    let timerSeconds = 0;
    let timerInterval = null;
    let isGameActive = false;
    let isAudioEnabled = true;
    
    // Audio Context (lazy loaded)
    let audioCtx = null;
    
    // Confetti
    let confetti = null;

    // Toast element
    const toastContainer = document.getElementById('toast-container');

    // DOM Elements
    const gridContainer = document.getElementById('grid-container');
    const boardOuterWrapper = document.querySelector('.board-outer-wrapper');
    const numberBank = document.getElementById('number-bank');
    const numberBankWrapper = document.getElementById('number-bank-wrapper');
    
    const targetSumDisplay = document.getElementById('target-sum');
    const bannerSumDisplay = document.getElementById('banner-sum');
    const timerDisplay = document.getElementById('game-timer');
    const moveCountDisplay = document.getElementById('move-count');
    
    const btnNewGame = document.getElementById('btn-new-game');
    const btnReset = document.getElementById('btn-reset');
    const btnHint = document.getElementById('btn-hint');
    const btnSolve = document.getElementById('btn-solve');
    
    const sizeButtons = document.querySelectorAll('.size-btn');
    const modeButtons = document.querySelectorAll('.mode-btn');
    const diffButtons = document.querySelectorAll('.diff-btn');
    
    const btnTutorial = document.getElementById('btn-tutorial');
    const modalTutorial = document.getElementById('modal-tutorial');
    const btnCloseTutorial = document.getElementById('btn-close-tutorial');
    const modalCloseButtons = document.querySelectorAll('.modal-close');
    
    const modalVictory = document.getElementById('modal-victory');
    const btnNextLevel = document.getElementById('btn-next-level');
    const btnShare = document.getElementById('btn-share');
    const victorySize = document.getElementById('victory-size');
    const victoryTime = document.getElementById('victory-time');
    const victoryMoves = document.getElementById('victory-moves');
    const victoryDiff = document.getElementById('victory-diff');

    const themeToggle = document.getElementById('theme-toggle');
    const themeDropdown = document.getElementById('theme-dropdown');
    const audioToggle = document.getElementById('audio-toggle');

    /* ==========================================================================
       Audio Synthesizer (Web Audio API)
       ========================================================================== */
    function initAudio() {
        if (!audioCtx) {
            audioCtx = new (window.AudioContext || window.webkitAudioContext)();
        }
    }

    function playSound(type) {
        if (!isAudioEnabled) return;
        initAudio();
        
        try {
            if (audioCtx.state === 'suspended') {
                audioCtx.resume();
            }
            
            const osc = audioCtx.createOscillator();
            const gain = audioCtx.createGain();
            osc.connect(gain);
            gain.connect(audioCtx.destination);
            
            const now = audioCtx.currentTime;
            
            switch (type) {
                case 'click':
                    osc.type = 'sine';
                    osc.frequency.setValueAtTime(500, now);
                    osc.frequency.exponentialRampToValueAtTime(150, now + 0.08);
                    gain.gain.setValueAtTime(0.08, now);
                    gain.gain.linearRampToValueAtTime(0, now + 0.08);
                    osc.start(now);
                    osc.stop(now + 0.08);
                    break;
                    
                case 'place':
                    osc.type = 'sine';
                    osc.frequency.setValueAtTime(650, now);
                    osc.frequency.exponentialRampToValueAtTime(350, now + 0.12);
                    gain.gain.setValueAtTime(0.12, now);
                    gain.gain.linearRampToValueAtTime(0, now + 0.12);
                    osc.start(now);
                    osc.stop(now + 0.12);
                    break;
                    
                case 'clear':
                    osc.type = 'sine';
                    osc.frequency.setValueAtTime(250, now);
                    osc.frequency.exponentialRampToValueAtTime(80, now + 0.12);
                    gain.gain.setValueAtTime(0.1, now);
                    gain.gain.linearRampToValueAtTime(0, now + 0.12);
                    osc.start(now);
                    osc.stop(now + 0.12);
                    break;
                    
                case 'swap':
                    osc.type = 'triangle';
                    osc.frequency.setValueAtTime(380, now);
                    osc.frequency.linearRampToValueAtTime(520, now + 0.08);
                    osc.frequency.linearRampToValueAtTime(280, now + 0.18);
                    gain.gain.setValueAtTime(0.1, now);
                    gain.gain.linearRampToValueAtTime(0, now + 0.18);
                    osc.start(now);
                    osc.stop(now + 0.18);
                    break;
                    
                case 'victory':
                    const notes = [261.63, 329.63, 392.00, 523.25, 659.25, 783.99, 1046.50]; // C Major chord arpeggio
                    notes.forEach((freq, idx) => {
                        const noteOsc = audioCtx.createOscillator();
                        const noteGain = audioCtx.createGain();
                        noteOsc.connect(noteGain);
                        noteGain.connect(audioCtx.destination);
                        
                        noteOsc.type = 'triangle';
                        noteOsc.frequency.setValueAtTime(freq, now + idx * 0.08);
                        
                        noteGain.gain.setValueAtTime(0, now);
                        noteGain.gain.linearRampToValueAtTime(0.12, now + idx * 0.08 + 0.02);
                        noteGain.gain.exponentialRampToValueAtTime(0.001, now + idx * 0.08 + 0.5);
                        
                        noteOsc.start(now + idx * 0.08);
                        noteOsc.stop(now + idx * 0.08 + 0.5);
                    });
                    break;
                    
                case 'hint':
                    osc.type = 'sine';
                    osc.frequency.setValueAtTime(440, now);
                    osc.frequency.linearRampToValueAtTime(880, now + 0.2);
                    gain.gain.setValueAtTime(0.08, now);
                    gain.gain.linearRampToValueAtTime(0, now + 0.2);
                    osc.start(now);
                    osc.stop(now + 0.2);
                    break;
                    
                case 'error':
                    osc.type = 'sawtooth';
                    osc.frequency.setValueAtTime(130, now);
                    gain.gain.setValueAtTime(0.1, now);
                    gain.gain.linearRampToValueAtTime(0, now + 0.2);
                    osc.start(now);
                    osc.stop(now + 0.2);
                    break;
            }
        } catch (e) {
            console.warn("Sound playback error:", e);
        }
    }

    /* ==========================================================================
       Toast & Feedback System
       ========================================================================== */
    function showToast(message, type = 'info') {
        const toast = document.createElement('div');
        toast.className = `toast toast-${type}`;
        
        let icon = 'fa-info-circle';
        if (type === 'success') icon = 'fa-check-circle';
        if (type === 'error') icon = 'fa-exclamation-triangle';
        
        toast.innerHTML = `<i class="fa-solid ${icon}"></i> <span>${message}</span>`;
        toastContainer.appendChild(toast);
        
        // Auto remove
        setTimeout(() => {
            toast.style.opacity = '0';
            toast.style.transform = 'translateY(-10px)';
            setTimeout(() => toast.remove(), 300);
        }, 3000);
    }

    /* ==========================================================================
       Math Magic Square Generators
       ========================================================================== */
    
    // Siamese Method for Odd Dimension Magic Squares (3x3 and 5x5)
    function generateOddMagicSquare(n) {
        const grid = Array(n).fill(null).map(() => Array(n).fill(0));
        let r = 0;
        let c = Math.floor(n / 2);
        
        for (let v = 1; v <= n * n; v++) {
            grid[r][c] = v;
            
            let nr = r - 1;
            let nc = c + 1;
            
            if (nr < 0 && nc >= n) {
                nr = r + 1;
                nc = c;
            } else {
                if (nr < 0) nr = n - 1;
                if (nc >= n) nc = 0;
            }
            
            if (grid[nr][nc] !== 0) {
                nr = r + 1;
                nc = c;
            }
            
            r = nr;
            c = nc;
        }
        
        // Flatten 2D to 1D
        return grid.flat();
    }
    
    // Doubly-Even Method for 4x4 Magic Square
    function generate4x4MagicSquare() {
        const arr = [];
        // Fill 1 to 16
        for (let i = 1; i <= 16; i++) {
            arr.push(i);
        }
        
        // Diagonals swap
        for (let i = 0; i < 16; i++) {
            const r = Math.floor(i / 4);
            const c = i % 4;
            
            // Check if element is on diagonals of the 4x4 grid
            if (r === c || r + c === 3) {
                arr[i] = 17 - arr[i];
            }
        }
        return arr;
    }
    
    // Scramble / Rotate / Reflect a Magic Square to introduce variety
    function transformMagicSquare(arr, n) {
        let grid = [];
        for (let i = 0; i < n; i++) {
            grid.push(arr.slice(i * n, (i + 1) * n));
        }
        
        // Helper: Rotate 90 deg clockwise
        const rotate90 = (matrix) => {
            const size = matrix.length;
            const res = Array(size).fill(null).map(() => Array(size).fill(0));
            for (let r = 0; r < size; r++) {
                for (let c = 0; c < size; c++) {
                    res[c][size - 1 - r] = matrix[r][c];
                }
            }
            return res;
        };
        
        // Helper: Horizontal reflect
        const reflectH = (matrix) => {
            return matrix.map(row => [...row].reverse());
        };

        // Random transformations
        const rotations = Math.floor(Math.random() * 4);
        const flip = Math.random() > 0.5;
        const invertNumbers = Math.random() > 0.5; // replace x with (N^2 + 1 - x)
        
        for (let i = 0; i < rotations; i++) {
            grid = rotate90(grid);
        }
        if (flip) {
            grid = reflectH(grid);
        }
        
        let flat = grid.flat();
        if (invertNumbers) {
            const maxVal = n * n + 1;
            flat = flat.map(x => maxVal - x);
        }
        
        return flat;
    }
    
    // Generate valid solution based on gridSize
    function generateSolution(n) {
        let baseSq;
        if (n === 3 || n === 5) {
            baseSq = generateOddMagicSquare(n);
        } else if (n === 4) {
            baseSq = generate4x4MagicSquare();
        }
        
        // Transform base square to get random orientation
        return transformMagicSquare(baseSq, n);
    }
    
    // Get Magic Constant
    function getMagicConstant(n) {
        return (n * (n * n + 1)) / 2;
    }

    /* ==========================================================================
       Game Initialization
       ========================================================================== */
    function initGame() {
        // Stop timer
        clearInterval(timerInterval);
        
        // Hide modals
        modalVictory.classList.add('hidden');
        if (confetti) confetti.stop();
        
        // Generate solution
        solution = generateSolution(gridSize);
        
        // Initialize state arrays
        const totalCells = gridSize * gridSize;
        board = Array(totalCells).fill(0);
        clues = Array(totalCells).fill(false);
        
        moveCount = 0;
        timerSeconds = 0;
        selectedBankNum = null;
        selectedGridCellIndex = null;
        isGameActive = true;
        
        updateStatsUI();
        
        // Create pre-filled clues depending on mode and difficulty
        if (gameMode === 'fill') {
            let clueCount = 0;
            if (difficulty === 'easy') {
                clueCount = Math.floor(totalCells * 0.5);
            } else if (difficulty === 'medium') {
                clueCount = Math.floor(totalCells * 0.3);
            }
            
            // Randomly select cell indices to lock as clues
            const indices = Array.from({ length: totalCells }, (_, i) => i);
            shuffleArray(indices);
            
            for (let i = 0; i < clueCount; i++) {
                const idx = indices[i];
                board[idx] = solution[idx];
                clues[idx] = true;
            }
        } else if (gameMode === 'swap') {
            // In Swap mode, grid is completely filled but scrambled
            board = [...solution];
            
            // Scramble cells that are not fixed clues
            // Note: in Swap mode, difficulty determines how many random swaps we perform
            let swapCount = 8;
            if (difficulty === 'medium') swapCount = 15;
            if (difficulty === 'hard') swapCount = 25;
            
            // Do random swaps to scramble
            for (let i = 0; i < swapCount; i++) {
                const idx1 = Math.floor(Math.random() * totalCells);
                const idx2 = Math.floor(Math.random() * totalCells);
                if (idx1 !== idx2) {
                    const temp = board[idx1];
                    board[idx1] = board[idx2];
                    board[idx2] = temp;
                }
            }
            
            // Optional: in Swap mode, easy difficulty could have a few fixed "anchor" cells
            if (difficulty === 'easy') {
                const anchorCount = Math.floor(totalCells * 0.25);
                const indices = Array.from({ length: totalCells }, (_, i) => i);
                shuffleArray(indices);
                for (let i = 0; i < anchorCount; i++) {
                    const idx = indices[i];
                    board[idx] = solution[idx];
                    clues[idx] = true; // locks this cell in place
                }
            }
        }
        
        // Set dynamic layout properties
        boardOuterWrapper.className = `board-outer-wrapper grid-${gridSize}x3`;
        
        // Render
        renderBoardGrid();
        renderNumberBank();
        calculateAndSetSums();
        
        // Start Timer
        startTimer();
    }
    
    function startTimer() {
        timerDisplay.innerText = '00:00';
        timerInterval = setInterval(() => {
            timerSeconds++;
            const mins = String(Math.floor(timerSeconds / 60)).padStart(2, '0');
            const secs = String(timerSeconds % 60).padStart(2, '0');
            timerDisplay.innerText = `${mins}:${secs}`;
        }, 1000);
    }
    
    function updateStatsUI() {
        const magicSum = getMagicConstant(gridSize);
        targetSumDisplay.innerText = magicSum;
        bannerSumDisplay.innerText = magicSum;
        moveCountDisplay.innerText = moveCount;
    }

    /* ==========================================================================
       Rendering Functions
       ========================================================================== */
    
    function renderBoardGrid() {
        // Clear all except diagonal indicators which we want to keep
        // Wait, it is cleaner to recreate the grid and indicators entirely
        boardOuterWrapper.innerHTML = '';
        
        const magicSum = getMagicConstant(gridSize);
        
        // 1. Create Diagonal 1 Indicator (Top-Left to Bottom-Right)
        const diag1 = document.createElement('div');
        diag1.className = 'diag-sum tl-br';
        diag1.id = 'sum-diag-1';
        diag1.title = '對角線總和 (左上至右下)';
        diag1.innerHTML = `<i class="fa-solid fa-arrow-down-right"></i><span class="sum-val">0</span>`;
        boardOuterWrapper.appendChild(diag1);
        
        // 2. Create Diagonal 2 Indicator (Top-Right to Bottom-Left)
        const diag2 = document.createElement('div');
        diag2.className = 'diag-sum tr-bl';
        diag2.id = 'sum-diag-2';
        diag2.title = '對角線總和 (右上至左下)';
        diag2.innerHTML = `<i class="fa-solid fa-arrow-down-left"></i><span class="sum-val">0</span>`;
        boardOuterWrapper.appendChild(diag2);
        
        // 3. Create Row indicators (on the right column N+2)
        for (let r = 0; r < gridSize; r++) {
            const rowSum = document.createElement('div');
            rowSum.className = 'sum-indicator row-indicator';
            rowSum.id = `sum-row-${r}`;
            rowSum.title = `第 ${r + 1} 行總和`;
            rowSum.style.gridRow = `${r + 2}`;
            rowSum.style.gridColumn = `${gridSize + 2}`;
            rowSum.innerText = '0';
            boardOuterWrapper.appendChild(rowSum);
        }
        
        // 4. Create Column indicators (on the bottom row N+2)
        for (let c = 0; c < gridSize; c++) {
            const colSum = document.createElement('div');
            colSum.className = 'sum-indicator col-indicator';
            colSum.id = `sum-col-${c}`;
            colSum.title = `第 ${c + 1} 列總和`;
            colSum.style.gridRow = `${gridSize + 2}`;
            colSum.style.gridColumn = `${c + 2}`;
            colSum.innerText = '0';
            boardOuterWrapper.appendChild(colSum);
        }
        
        // 5. Create Grid Cells
        for (let r = 0; r < gridSize; r++) {
            for (let c = 0; c < gridSize; c++) {
                const idx = r * gridSize + c;
                const cell = document.createElement('div');
                cell.className = 'grid-cell';
                cell.dataset.index = idx;
                cell.style.gridRow = `${r + 2}`;
                cell.style.gridColumn = `${c + 2}`;
                
                // Content
                updateCellContent(cell, idx);
                
                // Interaction event listeners
                setupCellEvents(cell, idx);
                
                boardOuterWrapper.appendChild(cell);
            }
        }
    }
    
    function updateCellContent(cell, idx) {
        cell.innerHTML = '';
        const val = board[idx];
        
        if (val !== 0) {
            const tile = document.createElement('div');
            tile.className = `tile-num ${clues[idx] ? 'fixed' : ''}`;
            tile.innerText = val;
            
            // Draggable setups
            if (!clues[idx]) {
                tile.setAttribute('draggable', 'true');
                
                // Drag start
                tile.addEventListener('dragstart', (e) => {
                    initAudio();
                    e.dataTransfer.setData('text/plain', JSON.stringify({ source: 'grid', index: idx, value: val }));
                    e.dataTransfer.effectAllowed = 'move';
                    cell.classList.add('selected');
                    selectedGridCellIndex = idx;
                    playSound('click');
                });
                
                tile.addEventListener('dragend', () => {
                    cell.classList.remove('selected');
                    selectedGridCellIndex = null;
                });
            }
            
            cell.appendChild(tile);
        }
    }
    
    function renderNumberBank() {
        if (gameMode === 'swap') {
            numberBankWrapper.classList.add('hidden');
            return;
        }
        numberBankWrapper.classList.remove('hidden');
        numberBank.innerHTML = '';
        
        const maxNum = gridSize * gridSize;
        
        // Find which numbers are already used
        const usedNumbers = new Set(board.filter(x => x !== 0));
        
        for (let i = 1; i <= maxNum; i++) {
            const tile = document.createElement('div');
            tile.className = 'bank-tile';
            tile.dataset.number = i;
            tile.innerText = i;
            
            if (usedNumbers.has(i)) {
                tile.classList.add('used');
            } else {
                tile.setAttribute('draggable', 'true');
                
                // Highlight selection on click
                tile.addEventListener('click', (e) => {
                    e.stopPropagation();
                    initAudio();
                    if (selectedBankNum === i) {
                        selectedBankNum = null;
                        tile.classList.remove('selected');
                        playSound('click');
                    } else {
                        // Deselect other
                        document.querySelectorAll('.bank-tile').forEach(t => t.classList.remove('selected'));
                        selectedBankNum = i;
                        tile.classList.add('selected');
                        playSound('click');
                    }
                });
                
                // Drag start events
                tile.addEventListener('dragstart', (e) => {
                    initAudio();
                    e.dataTransfer.setData('text/plain', JSON.stringify({ source: 'bank', value: i }));
                    e.dataTransfer.effectAllowed = 'copy';
                    
                    document.querySelectorAll('.bank-tile').forEach(t => t.classList.remove('selected'));
                    selectedBankNum = i;
                    tile.classList.add('selected');
                    playSound('click');
                });
                
                tile.addEventListener('dragend', () => {
                    tile.classList.remove('selected');
                    selectedBankNum = null;
                });
            }
            numberBank.appendChild(tile);
        }
    }

    /* ==========================================================================
       Grid Cell Interactivity (Events)
       ========================================================================== */
    function setupCellEvents(cell, idx) {
        // Drag Over
        cell.addEventListener('dragover', (e) => {
            if (clues[idx] || !isGameActive) return;
            e.preventDefault(); // necessary to allow drop
            cell.classList.add('selected');
        });
        
        // Drag Leave
        cell.addEventListener('dragleave', () => {
            cell.classList.remove('selected');
        });
        
        // Drop
        cell.addEventListener('drop', (e) => {
            if (clues[idx] || !isGameActive) return;
            e.preventDefault();
            cell.classList.remove('selected');
            
            try {
                const data = JSON.parse(e.dataTransfer.getData('text/plain'));
                if (data.source === 'bank') {
                    handlePlaceNum(idx, data.value);
                } else if (data.source === 'grid') {
                    handleMoveNum(data.index, idx);
                }
            } catch (err) {
                console.error("Drop error", err);
            }
        });
        
        // Mouse click placement / swap logic
        cell.addEventListener('click', (e) => {
            e.stopPropagation();
            if (!isGameActive) return;
            initAudio();
            
            if (clues[idx]) {
                playSound('error');
                showToast('這是關卡預設的數字，無法修改！', 'error');
                return;
            }
            
            if (gameMode === 'fill') {
                if (selectedBankNum !== null) {
                    // Place selected bank number here
                    handlePlaceNum(idx, selectedBankNum);
                    selectedBankNum = null;
                    document.querySelectorAll('.bank-tile').forEach(t => t.classList.remove('selected'));
                } else {
                    // Click on a cell with no bank tile selected: select this cell or clear it
                    if (board[idx] !== 0) {
                        // Double click clears, single click highlights/swaps?
                        // Let's toggle highlight for swap or just clear it on click if double-clicked
                        if (selectedGridCellIndex === null) {
                            selectedGridCellIndex = idx;
                            cell.classList.add('swap-source');
                            playSound('click');
                        } else if (selectedGridCellIndex === idx) {
                            selectedGridCellIndex = null;
                            cell.classList.remove('swap-source');
                            playSound('click');
                        } else {
                            // Swap internal grid cells
                            handleMoveNum(selectedGridCellIndex, idx);
                            document.querySelectorAll('.grid-cell').forEach(c => c.classList.remove('swap-source'));
                            selectedGridCellIndex = null;
                        }
                    }
                }
            } else if (gameMode === 'swap') {
                if (selectedGridCellIndex === null) {
                    // First click selects swap source
                    selectedGridCellIndex = idx;
                    cell.classList.add('swap-source');
                    playSound('click');
                } else {
                    // Second click swaps
                    if (selectedGridCellIndex === idx) {
                        // click same cell - cancel
                        selectedGridCellIndex = null;
                        cell.classList.remove('swap-source');
                        playSound('click');
                    } else {
                        handleMoveNum(selectedGridCellIndex, idx);
                        document.querySelectorAll('.grid-cell').forEach(c => c.classList.remove('swap-source'));
                        selectedGridCellIndex = null;
                    }
                }
            }
        });
        
        // Double click clears number in Fill Mode
        cell.addEventListener('dblclick', () => {
            if (!isGameActive || gameMode !== 'fill' || clues[idx]) return;
            if (board[idx] !== 0) {
                const clearedVal = board[idx];
                board[idx] = 0;
                moveCount++;
                updateStatsUI();
                updateCellContent(cell, idx);
                renderNumberBank();
                calculateAndSetSums();
                playSound('clear');
                showToast(`已清除數字 ${clearedVal}`, 'info');
            }
        });
    }

    /* ==========================================================================
       Game Actions Logics
       ========================================================================== */
    
    // Fill mode: Place number from bank into cell
    function handlePlaceNum(cellIdx, num) {
        const currentVal = board[cellIdx];
        
        // Update board
        board[cellIdx] = num;
        moveCount++;
        updateStatsUI();
        
        // Animate
        const cell = document.querySelector(`.grid-cell[data-index="${cellIdx}"]`);
        updateCellContent(cell, cellIdx);
        
        const tile = cell.querySelector('.tile-num');
        if (tile) tile.classList.add('placed-anim');
        
        renderNumberBank();
        calculateAndSetSums();
        playSound('place');
        
        checkWinCondition();
    }
    
    // Move / Swap number between two grid cells
    function handleMoveNum(fromIdx, toIdx) {
        if (clues[fromIdx] || clues[toIdx]) {
            playSound('error');
            return;
        }
        
        const temp = board[toIdx];
        board[toIdx] = board[fromIdx];
        board[fromIdx] = temp;
        
        moveCount++;
        updateStatsUI();
        
        // Update cells in DOM
        const cellFrom = document.querySelector(`.grid-cell[data-index="${fromIdx}"]`);
        const cellTo = document.querySelector(`.grid-cell[data-index="${toIdx}"]`);
        
        updateCellContent(cellFrom, fromIdx);
        updateCellContent(cellTo, toIdx);
        
        // Add animations
        const tileFrom = cellFrom.querySelector('.tile-num');
        const tileTo = cellTo.querySelector('.tile-num');
        if (tileFrom) tileFrom.classList.add('placed-anim');
        if (tileTo) tileTo.classList.add('placed-anim');
        
        if (gameMode === 'fill') {
            renderNumberBank();
        }
        
        calculateAndSetSums();
        playSound('swap');
        
        checkWinCondition();
    }

    /* ==========================================================================
       Math Verification (Sums computation & indicators updates)
       ========================================================================== */
    function calculateAndSetSums() {
        const magicSum = getMagicConstant(gridSize);
        
        // Initialize structures to hold sums
        const rowSums = Array(gridSize).fill(0);
        const colSums = Array(gridSize).fill(0);
        const rowCompletes = Array(gridSize).fill(true);
        const colCompletes = Array(gridSize).fill(true);
        
        let diag1Sum = 0;
        let diag2Sum = 0;
        let diag1Complete = true;
        let diag2Complete = true;
        
        // Calculate
        for (let r = 0; r < gridSize; r++) {
            for (let c = 0; c < gridSize; c++) {
                const idx = r * gridSize + c;
                const val = board[idx];
                
                if (val === 0) {
                    rowCompletes[r] = false;
                    colCompletes[c] = false;
                    if (r === c) diag1Complete = false;
                    if (r + c === gridSize - 1) diag2Complete = false;
                } else {
                    rowSums[r] += val;
                    colSums[c] += val;
                    if (r === c) diag1Sum += val;
                    if (r + c === gridSize - 1) diag2Sum += val;
                }
            }
        }
        
        // Update Row indicators
        for (let r = 0; r < gridSize; r++) {
            const indicator = document.getElementById(`sum-row-${r}`);
            if (!indicator) continue;
            
            indicator.innerText = rowSums[r];
            indicator.className = 'sum-indicator row-indicator';
            
            if (rowCompletes[r]) {
                if (rowSums[r] === magicSum) {
                    indicator.classList.add('correct');
                } else {
                    indicator.classList.add('incorrect');
                }
            } else if (rowSums[r] > 0) {
                indicator.classList.add('partial');
            }
        }
        
        // Update Col indicators
        for (let c = 0; c < gridSize; c++) {
            const indicator = document.getElementById(`sum-col-${c}`);
            if (!indicator) continue;
            
            indicator.innerText = colSums[c];
            indicator.className = 'sum-indicator col-indicator';
            
            if (colCompletes[c]) {
                if (colSums[c] === magicSum) {
                    indicator.classList.add('correct');
                } else {
                    indicator.classList.add('incorrect');
                }
            } else if (colSums[c] > 0) {
                indicator.classList.add('partial');
            }
        }
        
        // Update Diags indicators
        const diag1Indicator = document.getElementById('sum-diag-1');
        if (diag1Indicator) {
            diag1Indicator.querySelector('.sum-val').innerText = diag1Sum;
            diag1Indicator.className = 'diag-sum tl-br';
            
            if (diag1Complete) {
                if (diag1Sum === magicSum) {
                    diag1Indicator.classList.add('correct');
                } else {
                    diag1Indicator.classList.add('incorrect');
                }
            } else if (diag1Sum > 0) {
                diag1Indicator.classList.add('partial');
            }
        }
        
        const diag2Indicator = document.getElementById('sum-diag-2');
        if (diag2Indicator) {
            diag2Indicator.querySelector('.sum-val').innerText = diag2Sum;
            diag2Indicator.className = 'diag-sum tr-bl';
            
            if (diag2Complete) {
                if (diag2Sum === magicSum) {
                    diag2Indicator.classList.add('correct');
                } else {
                    diag2Indicator.classList.add('incorrect');
                }
            } else if (diag2Sum > 0) {
                diag2Indicator.classList.add('partial');
            }
        }
    }
    
    // Check if the board is successfully solved
    function checkWinCondition() {
        const magicSum = getMagicConstant(gridSize);
        const totalCells = gridSize * gridSize;
        
        // Check if all slots are filled
        if (board.some(x => x === 0)) return false;
        
        // Check Row Sums
        for (let r = 0; r < gridSize; r++) {
            let rowSum = 0;
            for (let c = 0; c < gridSize; c++) {
                rowSum += board[r * gridSize + c];
            }
            if (rowSum !== magicSum) return false;
        }
        
        // Check Col Sums
        for (let c = 0; c < gridSize; c++) {
            let colSum = 0;
            for (let r = 0; r < gridSize; r++) {
                colSum += board[r * gridSize + c];
            }
            if (colSum !== magicSum) return false;
        }
        
        // Check Diagonals
        let diag1Sum = 0;
        let diag2Sum = 0;
        for (let i = 0; i < gridSize; i++) {
            diag1Sum += board[i * gridSize + i];
            diag2Sum += board[i * gridSize + (gridSize - 1 - i)];
        }
        if (diag1Sum !== magicSum || diag2Sum !== magicSum) return false;
        
        // Check Unique numbers (1 to N^2)
        const numSet = new Set(board);
        if (numSet.size !== totalCells) return false;
        
        // If we reached here, victory!
        triggerVictory();
        return true;
    }
    
    function triggerVictory() {
        isGameActive = false;
        clearInterval(timerInterval);
        playSound('victory');
        
        // Setup stats in victory modal
        const mins = String(Math.floor(timerSeconds / 60)).padStart(2, '0');
        const secs = String(timerSeconds % 60).padStart(2, '0');
        
        victorySize.innerText = `${gridSize} x ${gridSize}`;
        victoryTime.innerText = `${mins}:${secs}`;
        victoryMoves.innerText = `${moveCount} 步`;
        
        let diffStr = '中級';
        if (difficulty === 'easy') diffStr = '初級';
        if (difficulty === 'hard') diffStr = '高級';
        victoryDiff.innerText = `${diffStr} (${gameMode === 'fill' ? '填數' : '置換'})`;
        
        // Display victory modal
        modalVictory.classList.remove('hidden');
        
        // Start confetti
        if (!confetti) {
            confetti = new ConfettiSystem('confetti-canvas');
        }
        confetti.start();
        showToast('太棒了！你解開了魔術方格！', 'success');
    }

    /* ==========================================================================
       Sidebar Actions (New Game, Hints, Solves, etc)
       ========================================================================== */
    
    // Hint System
    btnHint.addEventListener('click', () => {
        if (!isGameActive) return;
        initAudio();
        
        // Find indices that are not locked clues AND are either empty or incorrect
        const potentialIndices = [];
        for (let i = 0; i < board.length; i++) {
            if (!clues[i] && (board[i] === 0 || board[i] !== solution[i])) {
                potentialIndices.push(i);
            }
        }
        
        if (potentialIndices.length === 0) {
            showToast('所有格子的數字都已經是正確位置了！', 'info');
            return;
        }
        
        // Pick one index at random
        const targetIdx = potentialIndices[Math.floor(Math.random() * potentialIndices.length)];
        const correctVal = solution[targetIdx];
        
        // Inject hint into grid
        if (gameMode === 'fill') {
            // Find where this correct value currently is in the board (if anywhere) and clear it
            const currentIdxOfVal = board.indexOf(correctVal);
            if (currentIdxOfVal !== -1) {
                board[currentIdxOfVal] = 0;
                const cellPrev = document.querySelector(`.grid-cell[data-index="${currentIdxOfVal}"]`);
                updateCellContent(cellPrev, currentIdxOfVal);
            }
            
            board[targetIdx] = correctVal;
        } else if (gameMode === 'swap') {
            // In swap mode, the correct value MUST exist somewhere in the grid
            const currentIdxOfVal = board.indexOf(correctVal);
            if (currentIdxOfVal !== -1) {
                // Swap targetIdx content and currentIdxOfVal content
                const temp = board[targetIdx];
                board[targetIdx] = board[currentIdxOfVal];
                board[currentIdxOfVal] = temp;
                
                const cellPrev = document.querySelector(`.grid-cell[data-index="${currentIdxOfVal}"]`);
                updateCellContent(cellPrev, currentIdxOfVal);
            }
        }
        
        moveCount += 2; // Hints penalize move counts
        updateStatsUI();
        
        const cell = document.querySelector(`.grid-cell[data-index="${targetIdx}"]`);
        updateCellContent(cell, targetIdx);
        
        // Animate hint cell
        const tile = cell.querySelector('.tile-num');
        if (tile) {
            tile.classList.add('placed-anim');
            tile.style.boxShadow = '0 0 15px #ffb703';
            tile.style.borderColor = '#ffb703';
        }
        
        renderNumberBank();
        calculateAndSetSums();
        playSound('hint');
        showToast('已為你填入一個正確數字！(步數計為 +2)', 'info');
        
        checkWinCondition();
    });
    
    // Solve / Show Solution
    btnSolve.addEventListener('click', () => {
        if (!isGameActive) return;
        initAudio();
        
        if (confirm('確定要直接查看解答嗎？這將會終止本局計時與記錄。')) {
            isGameActive = false;
            clearInterval(timerInterval);
            
            // Set board to solution
            board = [...solution];
            renderBoardGrid();
            renderNumberBank();
            calculateAndSetSums();
            
            playSound('clear');
            showToast('已顯示正確答案，可以參考一下排列規律！', 'info');
        }
    });
    
    // Reset Board
    btnReset.addEventListener('click', () => {
        if (!isGameActive) return;
        initAudio();
        
        if (confirm('確定要將此關重置回最初狀態嗎？')) {
            // Re-initialize board values keeping clues
            const totalCells = gridSize * gridSize;
            
            if (gameMode === 'fill') {
                for (let i = 0; i < totalCells; i++) {
                    if (!clues[i]) {
                        board[i] = 0;
                    }
                }
            } else if (gameMode === 'swap') {
                // To reset swap mode, we would need to revert to original scrambled board.
                // For simplicity, let's re-scramble it (effectively a reset scramble).
                initGame();
                showToast('已重新洗牌重置！', 'info');
                return;
            }
            
            moveCount = 0;
            updateStatsUI();
            
            // Re-render
            for (let i = 0; i < totalCells; i++) {
                const cell = document.querySelector(`.grid-cell[data-index="${i}"]`);
                updateCellContent(cell, i);
            }
            
            renderNumberBank();
            calculateAndSetSums();
            playSound('clear');
            showToast('已還原本局！', 'info');
        }
    });
    
    // New game trigger
    btnNewGame.addEventListener('click', () => {
        initAudio();
        initGame();
        showToast('已為您開啟新局！', 'success');
    });

    /* ==========================================================================
       Sidebar Configuration Click Events
       ========================================================================== */
    
    // Grid Size selection
    sizeButtons.forEach(btn => {
        btn.addEventListener('click', () => {
            initAudio();
            const size = parseInt(btn.dataset.size);
            if (gridSize === size) return;
            
            sizeButtons.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            
            gridSize = size;
            initGame();
            showToast(`已切換至 ${gridSize}x${gridSize} 方陣`, 'info');
        });
    });
    
    // Game Mode selection
    modeButtons.forEach(btn => {
        btn.addEventListener('click', () => {
            initAudio();
            const mode = btn.dataset.mode;
            if (gameMode === mode) return;
            
            modeButtons.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            
            gameMode = mode;
            initGame();
            
            const modeName = mode === 'fill' ? '填數模式' : '置換模式';
            showToast(`已切換至 ${modeName}`, 'info');
        });
    });
    
    // Difficulty selection
    diffButtons.forEach(btn => {
        btn.addEventListener('click', () => {
            initAudio();
            const diff = btn.dataset.diff;
            if (difficulty === diff) return;
            
            diffButtons.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            
            difficulty = diff;
            initGame();
            
            let diffName = '中級';
            if (diff === 'easy') diffName = '初級';
            if (diff === 'hard') diffName = '高級';
            showToast(`已設定難度為：${diffName}`, 'info');
        });
    });

    /* ==========================================================================
       Modals Operations
       ========================================================================== */
    
    // Tutorial Modal
    btnTutorial.addEventListener('click', () => {
        initAudio();
        modalTutorial.classList.remove('hidden');
        playSound('click');
    });
    
    btnCloseTutorial.addEventListener('click', () => {
        initAudio();
        modalTutorial.classList.add('hidden');
        playSound('click');
    });
    
    // Generic close modal button
    modalCloseButtons.forEach(btn => {
        btn.addEventListener('click', () => {
            initAudio();
            document.querySelectorAll('.modal').forEach(m => m.classList.add('hidden'));
            if (confetti) confetti.stop();
            playSound('click');
        });
    });
    
    // Victory Next Level
    btnNextLevel.addEventListener('click', () => {
        initAudio();
        // Maybe increment grid size or just generate new puzzle
        initGame();
        showToast('新挑戰開始，加油！', 'success');
    });
    
    // Share achievement
    btnShare.addEventListener('click', () => {
        initAudio();
        const mins = String(Math.floor(timerSeconds / 60)).padStart(2, '0');
        const secs = String(timerSeconds % 60).padStart(2, '0');
        const text = `我剛剛在「魔術方框」數字益智遊戲中，以 ${mins}:${secs} 的時間、 ${moveCount} 步完成了 ${gridSize}x${gridSize} 的魔方陣！快來挑戰你的腦力邏輯！`;
        
        if (navigator.clipboard) {
            navigator.clipboard.writeText(text).then(() => {
                showToast('已複製成就訊息到剪貼簿，快分享給朋友吧！', 'success');
            }).catch(() => {
                alert(text);
            });
        } else {
            alert(text);
        }
        playSound('click');
    });

    // Close dropdown on click outside
    document.addEventListener('click', () => {
        themeDropdown.classList.add('hidden');
    });

    /* ==========================================================================
       Themes & Audio Toggles
       ========================================================================== */
    themeToggle.addEventListener('click', (e) => {
        e.stopPropagation();
        initAudio();
        themeDropdown.classList.toggle('hidden');
        playSound('click');
    });
    
    document.querySelectorAll('.theme-opt').forEach(btn => {
        btn.addEventListener('click', () => {
            initAudio();
            const theme = btn.dataset.theme;
            
            // Remove active classes
            document.querySelectorAll('.theme-opt').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            
            // Set body class
            document.body.className = `theme-${theme}`;
            themeDropdown.classList.add('hidden');
            playSound('click');
            showToast(`已切換主題：${btn.innerText.trim()}`, 'info');
        });
    });
    
    audioToggle.addEventListener('click', () => {
        initAudio();
        isAudioEnabled = !isAudioEnabled;
        
        if (isAudioEnabled) {
            audioToggle.innerHTML = '<i class="fa-solid fa-volume-high"></i>';
            showToast('音效已開啟', 'info');
            playSound('click');
        } else {
            audioToggle.innerHTML = '<i class="fa-solid fa-volume-xmark"></i>';
            showToast('音效已靜音', 'info');
        }
    });

    /* ==========================================================================
       Utility Functions
       ========================================================================== */
    function shuffleArray(array) {
        for (let i = array.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [array[i], array[j]] = [array[j], array[i]];
        }
    }

    // Body click clears selections
    document.body.addEventListener('click', () => {
        selectedBankNum = null;
        selectedGridCellIndex = null;
        document.querySelectorAll('.bank-tile').forEach(t => t.classList.remove('selected'));
        document.querySelectorAll('.grid-cell').forEach(c => c.classList.remove('swap-source'));
    });

    // Keyboard controls (press Esc to close modals)
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape') {
            document.querySelectorAll('.modal').forEach(m => m.classList.add('hidden'));
            if (confetti) confetti.stop();
        }
    });

    // Start!
    initGame();
});
